export default [
    {
        "_id": 123, "topic": "Space",
        "userName": "SpaceX",
        "handle": "@spacex",
        "time": "2h",
        "image": "spacex.jpg",
        "title": "SpaceX's Mission",
        "tuit": "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars",
        "liked": true,
        "likes": 2345,
        "disliked": false,
        "dislikes": 1024,
        "replies": 123,
        "retuits": 432
    },
    {
        "_id": 234,
        "topic": "Traffic",
        "userName": "MBTA",
        "handle": "@mbta", "time": "2h", "image": "T.png",
        "title": "The MBTA fixing traffic",
        "tuit": "The MBTA has projects in progress and proposed projects are designed for intra-city ('loop') transit systems.",
        "liked": true,
        "likes": 2345,
        "disliked": false,
        "dislikes": 1024,
        "replies": 321,
        "retuits": 432
    },
    {
        "_id": 345,
        "topic": "Space",
        "userName": "Tesla",
        "title": "Tesla Cybertruck lands on Mars and picks up the Curiosity rover on its 6' bed",
        "time": "2h",
        "image": "tesla.png",
        "liked": false,
        "disliked": true,
        "dislikes": 14,
        "replies": 123,
        "retuits": 432,
        "likes": 234,
        "handle": "@tesla",
        "tuit": "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars"
    },
    {
        "_id": 456,
        "topic": "Space",
        "userName": "SpaceX",
        "title": "100s of SpaceX Starships land on Mars after a 6 month journey. 1000s of Martian colonists being building Mars Base 1",
        "time": "2h",
        "image": "spacex.jpg",
        "liked": true,
        "replies": 67,
        "retuits": 3,
        "likes": 913,
        "disliked": false,
        "dislikes": 1024,
        "handle": "@spacex",
        "tuit": "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars"
    },
    {
        "_id": 567,
        "topic": "Energy",
        "userName": "Tesla",
        "title": "Tesla FSD finally makes driving obsolete. After years of delay, Tesla Full Self Driving can drive you to work while you work, play, or sleep",
        "time": "4d",
        "image": "tesla.png",
        "liked": false,
        "disliked": true,
        "dislikes": 1024,
        "replies": 123,
        "retuits": 432,
        "likes": 2345,
        "handle": "@spacex",
        "tuit": "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars"
    }
];
